name: .NET Build and Test

on:
  push:
    branches: [ "main", "feature" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ./azdevsops11/azdevsops11.sln
      
    - name: Build
      run: dotnet build ./azdevsops11/azdevsops11.sln --no-restore --configuration Release
      
    - name: Test
      run: dotnet test ./azdevsops11/azdevsops11.sln --no-build --configuration Release --verbosity normal
      
    - name: Publish
      run: dotnet publish ./azdevsops11/azdevsops11.sln -c Release -o publish/
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: publish/
